### ISSUE TITLE
how to install this package ?

### ISSUE THREAD

**Issue by WinterLi1993** [nijibabulu/pypysam#1]
HI,
   how to install your package in my pypy ?

**Comment by nijibabulu** [comment]
I have updated the README.md file to include some basic installation instructions. Most of this is covered in the setuptools documentation. Please let me know if you need additional help and feel free to write up any bug reports directly to me. This software is only partially implemented.

**Comment by WinterLi1993** [comment]
HI ,
   what about the speed of the pypysam ,comparing wth pysam ?  I find it's written by python,,,not a htslib wrapper .

**Comment by nijibabulu** [comment]
Pypysam cannot run as fast as pysam, but it allows you to write python scripts compatible with pypy that parse and write to BAM files. Therefore if the computation in your script takes longer than the parsing time, this would be useful.

**Comment by WinterLi1993** [comment]
got , maybe  we can have a try to write  a C wrapper pypysam  for pypy ?
